language: node_js
node_js:
 - "10"
branches:
  only:
    - master
install:
 - npm install -g firebase-tools
 - npm i
script:
 - npm run build
after_success:
 - firebase deploy --token $FIREBASE_TOKEN
