language: node_js
node_js:
 - "10"
branches:
  only:
    - master
install:
 - echo $FIREBASE_TOKEN
 - echo FIREBASE_TOKEN
 - npm install -g firebase-tools
 - npm install -g tslint
 - npm i
 - npm install --prefix ./functions
script:
 - firebase use anim-trader
 - npm run build
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  project: "anim-trader"
